version: '3.5'

services:
  db:
    image: mysql:5.7
    container_name: db-container
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
#      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
#      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: batch
      MYSQL_USER: batch
      MYSQL_PASSWORD: batch
    ports:
      - '3306:3306'
    expose:
      - 3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10